import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import Navbar from "./_components/Navbar";
import { ThemeProvider } from "@mui/material";
import theme from "./theme";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "LuxeVista",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <ThemeProvider theme={theme}>
          <TRPCReactProvider>
            <>
              <Navbar />
              {children}
            </>
          </TRPCReactProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
